language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
deploy:
  fqdn: gfe.wiki
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  token: $duan
  keep_history: true
  on:
    branch: master
    #ddd