language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm install && npm run build && cd docs/.vuepress/dist && echo 'gui.wiki' > CNAME && cd - 
deploy:
  fqdn: gfe.wiki
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master